### ISSUE TITLE
Facebook API v 2.x support

### ISSUE THREAD

**Issue by mevjak** [wlepinski/angularjs-facebook-sdk#5]
According to Facebook API changelog there are some changes in Facebook SDK loading:

1) The location https://connect.facebook.net/en_US/all.js become https://connect.facebook.net/en_US/sdk.js in v 2.0 and above.

2) There is a new parameter in FB.init() that indicates what version of the API will be used

See: https://developers.facebook.com/docs/apps/changelog#v2_0_js_sdk

IMHO the fix would require some small changes in facebook_config_provider service.

**Comment by wlepinski** [comment]
Will take a look as soon as possible. 
In the meantime, @mevjak if you could provide a pull request for that would be awesome.

**Comment by mevjak** [comment]
Pull request submitted - https://github.com/wlepinski/angularjs-facebook-sdk/pull/6.

**Comment by wlepinski** [comment]
Hey, Thanks for the PR. I'll take a look as soon as possible.

**Comment by wlepinski** [comment]
Merged on 02c1bd0.
